### PR TITLE
fix domain socket error on windows

### PR DESCRIPTION
**Pull request by zhscn**
Hi @binghe do you have some suggestions on supporting domain socket on windows? Seems it's better to implement it for upstream.

### CODE REVIEW

**Comment by binghe** [comment]
Hi,

I think one option here is to use FFI to call the AF_UNIX-related Windows functions from the their DLLs (`ws2_32`?) usocket has already some FFI code for implementing `wait-for-input` on SBCL/Windows, it should be natural to add a few more.  I think, with some careful coding, usocket may still work on Windows 7.  (You may also ask SBCL people to see if they can directly support AF_UNIX on Windows.)

Thus, instead of merging the present PR, I'd prefer to push the work on supporting AF_UNIX on SBCL/Windows.  (My personal priority would be to first try to make LispWorks supported.)

Chun

**Comment by zhscn** [comment]
> instead of merging the present PR, I'd prefer to push the work on supporting AF_UNIX on SBCL/Windows

Prior PR introduced compile error, this PR is to fix it before supporting AF_UNIX on Windows:
```
* (ql:quickload :usocket)
To load "usocket":
  Load 1 ASDF system:
    usocket
; Loading "usocket"
[package usocket].....;
; caught ERROR:
;   READ error during COMPILE-FILE:
;
;     Symbol "LOCAL-SOCKET" not found in the SB-BSD-SOCKETS package.
;
;       Line: 440, Column: 68, File-Position: 16707
;
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file C:\\Users\\zhscn\\common-lisp\\usocket\\backend\\sbcl.lisp" {23689519}>
 
debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {234E0001}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "usocket" "backend" "sbcl">
 
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
 
restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "usocket" "backend" "sbcl">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "usocket" "backend" "sbcl">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4:                                 Retry ASDF operation.
  5:                                 Retry ASDF operation after resetting the
                                     configuration.
  6: [ABORT                        ] Give up on "usocket"
  7: [REGISTER-LOCAL-PROJECTS      ] Register local projects and try again.
  8:                                 Exit debugger, returning to top level.
 
(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "usocket" "backend" "sbcl">)))
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL
```

**Comment by zhscn** [comment]
> I think, with some careful coding, usocket may still work on Windows 7.

I'm confused with it, how does it work on Windows 7? Anyway, I'll try the FFI approach first.

**Comment by binghe** [comment]
> > I think, with some careful coding, usocket may still work on Windows 7.
> 
> I'm confused with it, how does it work on Windows 7? Anyway, I'll try the FFI approach first.

I meant that usocket should compile and load without any issue on SBCL/Windows 7, without support of `AF_UNIX` on it. The above issue should be fixed in a better way on Windows 10 by actually supporting `AF_UNIX`, but now I realized that your code changes here will make usocket at least loadable on SBCL/Windows, thus I'm going to merge it first. Thanks.

**Pull request merged**
