### PR TITLE
Fix the call to get-socket-broadcast in LW backend

### PR DESCRIPTION
**Pull request by varjagg**

### CODE REVIEW

**Comment by binghe** [comment]
An embarrassing bug ... thanks for the fix!

**Comment by binghe** [comment]
Manually merged as 58203ca2c0053b067d60331654e9ddf6faa24648

**Comment by varjagg** [comment]
Thanks and no need to apologize: I believe I introduced this one myself :blush:

**Comment by binghe** [comment]
> Thanks and no need to apologize: I believe I introduced this one myself 😊

I could have reviewed your code changes more carefully. In fact, I'm a bit lazy in recent years when maintaining this package, because currently I'm not using Common Lisp anywhere else, besides most of my "energy" were spent on formalized mathematics (see, e.g. https://github.com/HOL-Theorem-Prover/HOL/pull/910).

Anyway, I should pick a weekend to focus on usocket and close pending open issues, if not all.

**Pull request closed without merging**
