### PR TITLE
Add support for genera.

### PR DESCRIPTION
**Pull request by Symbolics**
Seems Genera is undergoing a resurgence of sorts. This pull request adds support for this platform to usocket.

### CODE REVIEW

**Comment by binghe** [comment]
Amazing ... thanks for this contribution!

**Comment by binghe** [comment]
Hi,

Currently I can't test your code in VLM, but the following code looks strange:

```
(defun %add-waiter (wait-list waiter)
  (declare (ignore wait-list waiter)))

(defun %remove-waiter (wait-list waiter)
  (push (socket waiter) (wait-list-%wait wait-list)))
```

Usually we push a socket into the waiter in `%add-waiter` and pop it in `%remove-waiter`.  Can you confirm this?

Chun

**Comment by Symbolics** [comment]
Hi,

I forwarded this note to @gmpalter (github ID). He is the original author of the code.

I cannot comment on the correctness, but I do use usockets daily on Genera and have not found any problems with it so far.

**Comment by binghe** [comment]
Hi... thanks, then let me know his reply. --Chun

**Comment by Symbolics** [comment]
Reply from Gary:

> The %remove-waiter function should do nothing just like %add-waiter.  (There’s no implementation-specific code needed for Genera here.)

**Comment by binghe** [comment]
Thanks, then I fix `%remove-waiter` with empty function body.

**Pull request merged**
